sensor:
  ros__parameters:
    camera_name: 'camera_right'
    exposure_time: 5000
    image_width: 640
    image_height: 480
    gain: 32.0
    imu_usb_hid: 'USB VID:PID=0483:5740 SNR=396B37573137'
    camera_config_url: 'camera/MV-CH100-60UC_DA2152113.mfs' #最好写成绝对路径！
    fps: 100